# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-10 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.SmallIntegerField(choices=[(1, '气体'), (1, '液体'), (1, '蒸汽')], verbose_name='流类型')),
                ('pipe_id_min', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='D管道内径最小值')),
                ('pipe_id_max', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='D管道内径最大值')),
                ('factor', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='F系数')),
            ],
        ),
    ]
