# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-27 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'verbose_name': 'F系数', 'verbose_name_plural': 'F系数'},
        ),
        migrations.AlterField(
            model_name='factor',
            name='flow_type',
            field=models.CharField(max_length=10, verbose_name='流类型'),
        ),
    ]
