# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-10 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210102_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationhistory',
            name='flow_factor',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='F系数'),
        ),
    ]
